[reticulum]
  enable_transport = no
  share_instance = no
  respond_to_probes = yes

[logging]
  loglevel = 5

[interfaces]
  [[Email Transport]]
    type = PipeInterface
    enabled = yes
    command = /usr/local/bin/rns-over-email --smtp-host mail --smtp-port 3025 --smtp-username bob@demo.local --smtp-password-file /run/secrets/password --smtp-from bob@demo.local --smtp-tls none --imap-host mail --imap-port 3143 --imap-username bob@demo.local --imap-password-file /run/secrets/password --imap-tls none --peer-email alice@demo.local --imap-poll-interval 5s --log-level debug
    respawn_delay = 5
